server:
  port: 8080

spring:
  jackson:
    serialization:
      indent_output: true

builder:
  metro:
    enabled: true
    datasource:
      url: jdbc:mysql://test-metro-db.cyi4arp1bouk.eu-west-1.rds.amazonaws.com:3306/metro?useSSL=true&requireSSL=true
      username: mastermetro
      password: DOQmUyfeuOQp3TIjr4NJ
      driver-class-name: com.mysql.cj.jdbc.Driver
  translation:
    provider: google  # google or openai
    google:
      apiKey: ${GOOGLE_TRANSLATE_API_KEY:}
    openai:
      apiUrl: https://api.openai.com/v1/chat/completions
      apiKey: ${OPENAI_API_KEY:}
      model: gpt-4o-mini
